services:
  - type: web
    name: sistem-laporan
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn sistem_laporan.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: sistem_laporan.settings
      - key: SECRET_KEY
        value: django-insecure-x7et^nhk=l&g+mja__k--p^5qes*19@r2i)xv&$!r-y!e_pb@7
